### ISSUE TITLE
github readme and dockerhub readme have different variable names all over

### ISSUE THREAD

**Issue by brandonros** [jnovack/docker-autossh#20]

**Comment by jnovack** [comment]
examples please

**Comment by brandonros** [comment]
github:

![image](https://user-images.githubusercontent.com/8949910/89322757-b5900b80-d652-11ea-966b-bfb66fbb1f75.png)


![image](https://user-images.githubusercontent.com/8949910/89322759-b6c13880-d652-11ea-8405-cf996e029869.png)

dockerhub:

![image](https://user-images.githubusercontent.com/8949910/89322783-bf197380-d652-11ea-8d01-b722c7085034.png)

![image](https://user-images.githubusercontent.com/8949910/89322798-c771ae80-d652-11ea-8dbb-647a2dd27d27.png)

**Comment by brandonros** [comment]
SSH_HOSTUSER versus SSH+REMOTE_USER, v1.2.0 versus v2.0.0

your doucmentation is out of sync. dockerhub is ahead of github

**Comment by jnovack** [comment]
different branches.  v2.0.0 is not 'latest' because it's not published.
