### ISSUE TITLE
question about "ExitOnForwardFailure yes"

### ISSUE THREAD

**Issue by eisler** [jnovack/docker-autossh#9]
is there a difference between "ExitOnForwardFailure yes" and "ExitOnForwardFailure=yes"?

**Comment by jnovack** [comment]
Yes, laziness and inconsistency. #mybad

`-o ExitOnForwardFailure=yes` and `-o "ExitOnForwardFailure yes"` is the same thing.

Semantically, the one with the `=` sign is a "command-line option", while the one with the `"` (quotes) is a configuration file option. 

In some applications, environment variables may overwrite command-line options may overwrite configuration file options.  There could be some hierarchy.  I do not know if `ssh(1)` has that case, I certainly did not write it with a hierarchy in mind, it was just pure laziness in not making it consistent.
